### ISSUE TITLE
Locale/encoding error in ruby

### ISSUE THREAD

**Issue by famousketchup** [KeyboardFire/ppi3#1]
Greetings.
Got to using ppi3 instead of i3bang just like in your i3 `_config`.
Everything works fine, apart from reloading config with `ppi3` via keybinding in `config`:
```
/usr/bin/ppi3:47:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/bin/ppi3:47:in `preprocess'
	from /usr/bin/ppi3:148:in `<main>'
```

I fixed it by adding this to `/usr/bin/ppi3`:
```ruby
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

Should I reason with it the other way or I can send you a pull request? 💭

**Comment by tckmn** [comment]
A pull request would be great, thanks! :)

**Comment by famousketchup** [comment]
There you go! Thank you for your work. It's a pleasure to use your i3 tools ^^

**Comment by tckmn** [comment]
Thanks, it's great to know that other people are finding my projects useful even though they're only personal ones!
